package book.r03;

public enum Wojewodztwo {
    LUBUSKIE,
    LUBELSKIE,
    LODZKIE,
    POMORSKIE,
    ZACHODNIOPOMORSKIE,
    KUJAWSKOPOMORSKIE,
    WARMINSKOMAZURSKIE,
    WIELKOPOLSKIE,
    SWIETOKRZYSKIE,
    MALOPOLSKIE,
    SLASKIE,
    OPOLSKIE,
    DOLNOSLASKIE,
    PODKARPACKIE
}
